# Generated by Django 5.0.6 on 2024-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full_name')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('phone_number', models.CharField(max_length=50, verbose_name='phone_number')),
                ('address', models.CharField(max_length=256, verbose_name='address')),
                ('evelator_speech', models.TextField(verbose_name='evelator_speech')),
                ('cv', models.FileField(upload_to='', verbose_name='cv')),
                ('selected', models.BooleanField(default=False, verbose_name='selected')),
                ('employed', models.BooleanField(default=False, verbose_name='employed')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
