# Generated by Django 5.0.6 on 2024-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_slug', models.SlugField(default='null')),
                ('description', models.TextField()),
                ('keywords', models.CharField(default='null', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_source', models.CharField(blank=True, max_length=255, null=True)),
                ('image_description', models.CharField(blank=True, default='image', max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('publish', models.BooleanField(default=False)),
                ('still_open', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-pub_date'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=156, verbose_name='Name')),
                ('description', models.TextField(default='null')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'managed': True,
            },
        ),
    ]
